steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/dialectica-tacitus/dialectica/api:latest', '-f', 'packages/api/Dockerfile', '.']
images:
  - 'us-east1-docker.pkg.dev/dialectica-tacitus/dialectica/api:latest'
