"use client";

import { Brain } from "lucide-react";

type AutoReasoning = {
  graph_stats?: { total_nodes: number; total_edges: number };
  escalation?: {
    current_stage?: number | null;
    direction?: string | null;
    velocity?: number | null;
  };
  top_actors?: string[];
  assessment?: unknown;
};

interface Props {
  reasoning?: AutoReasoning | null;
}

export default function AutoReasoningPanel({ reasoning }: Props) {
  if (!reasoning) return null;
  const { graph_stats, escalation, top_actors, assessment } = reasoning;

  return (
    <div className="card space-y-3">
      <h3 className="text-sm font-semibold text-text-primary flex items-center gap-2">
        <Brain size={14} /> First-pass analysis
      </h3>
      <p className="text-xs text-text-secondary">
        Auto-generated by the reasoning engine on completion. Open the workspace to dig deeper.
      </p>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs">
        {graph_stats && (
          <>
            <Stat label="Nodes" value={graph_stats.total_nodes} />
            <Stat label="Edges" value={graph_stats.total_edges} />
          </>
        )}
        {escalation?.current_stage != null && (
          <Stat label="Glasl stage" value={String(escalation.current_stage)} />
        )}
        {escalation?.direction && <Stat label="Direction" value={escalation.direction} />}
      </div>

      {top_actors && top_actors.length > 0 && (
        <div>
          <div className="text-[10px] uppercase tracking-wide text-text-secondary mb-1">
            Top actors
          </div>
          <div className="flex flex-wrap gap-1.5">
            {top_actors.map((name, i) => (
              <span
                key={i}
                className="px-1.5 py-0.5 rounded bg-surface text-xs text-text-primary"
              >
                {name || "—"}
              </span>
            ))}
          </div>
        </div>
      )}

      {typeof assessment === "string" && assessment.trim() && (
        <div className="text-sm text-text-primary leading-relaxed border-l-2 border-accent pl-3">
          {assessment}
        </div>
      )}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="px-2.5 py-1.5 rounded border border-border">
      <div className="text-[10px] uppercase tracking-wide text-text-secondary">{label}</div>
      <div className="text-sm font-semibold text-text-primary tabular-nums">{value}</div>
    </div>
  );
}
