import type { GraphData, GraphLink, GraphNode } from "@/types/graph";
import type { DemoScenarioId } from "../data/doors";
import type {
  CuratedReasoningQuestion,
  ReasoningResultFixture,
  ReasoningScenario,
  SimilarityNeighbor,
} from "./types";

const capturedAt = "2026-05-03T12:00:00Z";

function node(id: string, name: string, node_type: GraphNode["node_type"], confidence = 0.9): GraphNode {
  return {
    id,
    label: name,
    name,
    node_type,
    confidence,
    properties: { confidence, centrality: 0.65 },
  };
}

function edge(
  id: string,
  source: string,
  target: string,
  edge_type: string,
  weight = 0.8,
  confidence = 0.86
): GraphLink {
  return { id, source, target, edge_type, weight, confidence };
}

const GRAPHS: Record<DemoScenarioId, GraphData> = {
  romeo: {
    nodes: [
      node("act_romeo", "Romeo Montague", "actor"),
      node("act_juliet", "Juliet Capulet", "actor"),
      node("act_tybalt", "Tybalt Capulet", "actor"),
      node("act_friar", "Friar Lawrence", "actor"),
      node("evt_brawl", "Street brawl", "event"),
      node("evt_mercutio_death", "Mercutio death", "event"),
      node("evt_tybalt_death", "Tybalt death", "event"),
      node("evt_banishment", "Romeo banishment", "event"),
      node("conf_verona", "Montague-Capulet feud", "conflict"),
      node("norm_prince_order", "Prince's civic order", "norm"),
      node("int_dynastic", "Dynastic continuity", "interest"),
    ],
    links: [
      edge("ed_brawl_causes_mercutio", "evt_brawl", "evt_mercutio_death", "CAUSED"),
      edge("ed_mercutio_causes_tybalt", "evt_mercutio_death", "evt_tybalt_death", "CAUSED"),
      edge("ed_tybalt_causes_banish", "evt_tybalt_death", "evt_banishment", "CAUSED"),
      edge("ed_tybalt_opposes_romeo", "act_tybalt", "act_romeo", "OPPOSED_TO"),
      edge("ed_friar_mediates", "act_friar", "conf_verona", "RESOLVED_THROUGH"),
      edge("ed_capulet_interest", "int_dynastic", "act_juliet", "HAS_INTEREST"),
      edge("ed_banish_violates", "evt_banishment", "norm_prince_order", "GOVERNED_BY"),
    ],
  },
  war_peace: {
    nodes: [
      node("act_napoleon", "Napoleon", "actor"),
      node("act_kutuzov", "Kutuzov", "actor"),
      node("act_alexander", "Alexander I", "actor"),
      node("evt_niemen", "Niemen crossing", "event"),
      node("evt_smolensk", "Smolensk advance", "event"),
      node("evt_borodino", "Borodino", "event"),
      node("evt_moscow", "Moscow burning", "event"),
      node("evt_berezina", "Berezina retreat", "event"),
      node("conf_1812", "Napoleon-Russia 1812", "conflict"),
      node("pow_attrition", "Attrition advantage", "power_dynamic"),
      node("nar_great_man", "Great man theory", "narrative"),
    ],
    links: [
      edge("ed_niemen_smolensk", "evt_niemen", "evt_smolensk", "CAUSED"),
      edge("ed_smolensk_borodino", "evt_smolensk", "evt_borodino", "CAUSED"),
      edge("ed_borodino_moscow", "evt_borodino", "evt_moscow", "CAUSED"),
      edge("ed_moscow_berezina", "evt_moscow", "evt_berezina", "CAUSED"),
      edge("ed_napoleon_advances", "act_napoleon", "evt_smolensk", "PERFORMED"),
      edge("ed_kutuzov_batna", "act_kutuzov", "pow_attrition", "HAS_POWER_OVER"),
      edge("ed_tolstoy_frame", "nar_great_man", "conf_1812", "ABOUT"),
    ],
  },
  syria: {
    nodes: [
      node("act_assad", "Assad regime", "actor"),
      node("act_russia", "Russia", "actor"),
      node("act_iran", "Iran", "actor"),
      node("act_turkey", "Turkey", "actor"),
      node("act_hts", "HTS", "actor"),
      node("act_sdf", "SDF", "actor"),
      node("evt_daraa", "Daraa protests", "event"),
      node("evt_ghouta", "Ghouta chemical attack", "event"),
      node("evt_russia_2015", "Russian intervention", "event"),
      node("evt_aleppo", "Aleppo fall", "event"),
      node("evt_astana", "Astana process", "process"),
      node("evt_hts_2024", "HTS 2024 offensive", "event"),
      node("conf_syria", "Syria civil war", "conflict"),
      node("norm_cwc", "Chemical weapons norm", "norm"),
      node("int_corridor", "Iranian corridor", "interest"),
    ],
    links: [
      edge("ed_daraa_conflict", "evt_daraa", "conf_syria", "CAUSED"),
      edge("ed_ghouta_norm", "evt_ghouta", "norm_cwc", "VIOLATES"),
      edge("ed_russia_aleppo", "evt_russia_2015", "evt_aleppo", "CAUSED"),
      edge("ed_aleppo_astana", "evt_aleppo", "evt_astana", "CAUSED"),
      edge("ed_russia_assad", "act_russia", "act_assad", "HAS_POWER_OVER"),
      edge("ed_iran_corridor", "act_iran", "int_corridor", "HAS_INTEREST"),
      edge("ed_turkey_hts", "act_turkey", "act_hts", "HAS_POWER_OVER"),
      edge("ed_hts_offensive", "act_hts", "evt_hts_2024", "PERFORMED"),
      edge("ed_hts_collapse", "evt_hts_2024", "act_assad", "TARGETED"),
    ],
  },
};

function result(
  qid: string,
  framework: string,
  summary: string,
  full: string,
  nodeIds: string[],
  edgeIds: string[],
  rules: string[],
  confidence = 0.86,
  determinism = 0.88,
  risk = 0.08
): ReasoningResultFixture {
  return {
    question_id: qid,
    answer_summary: summary,
    answer_full: full,
    confidence,
    determinism_score: determinism,
    primary_framework: framework,
    cited_node_ids: nodeIds,
    cited_edge_ids: edgeIds,
    cypher_queries: [
      "MATCH (n {workspace_id: $workspace_id, tenant_id: $tenant_id}) RETURN n LIMIT 50",
      "MATCH p=(a)-[r*1..4]->(b) WHERE a.id IN $seed_ids RETURN p",
    ],
    symbolic_rules_fired: rules,
    hallucination_risk: risk,
    elapsed_ms: Math.round(180 + confidence * 140),
    cost_usd: 0.0012,
  };
}

function llm(answer: string) {
  return {
    model: "gpt-4o-2024-11-20",
    captured_at: capturedAt,
    system_prompt: "Answer concisely with citations.",
    answer,
    tokens: 420,
    wall_clock_ms: 4100,
  };
}

const vendettaSimilarity: SimilarityNeighbor[] = [
  {
    workspace_id: "corpus-vendetta-hatfield-mccoy",
    conflict_name: "Hatfield-McCoy feud",
    semantic_dist: 0.14,
    topological_dist: 0.22,
    combined_dist: 0.18,
    explanation:
      "Mercutio_death maps to the kin-retaliation bridge event: a personal death closes the mediator path and reopens a family-coded revenge loop.",
  },
  {
    workspace_id: "corpus-vendetta-gjakmarrja",
    conflict_name: "Albanian gjakmarrja",
    semantic_dist: 0.19,
    topological_dist: 0.23,
    combined_dist: 0.21,
    explanation:
      "The topology matches honor obligation plus weak adjudication: a norm node substitutes for enforceable civic authority.",
  },
  {
    workspace_id: "corpus-vendetta-badal",
    conflict_name: "Pashtun badal cycles",
    semantic_dist: 0.25,
    topological_dist: 0.29,
    combined_dist: 0.27,
    explanation:
      "The comparison case shares revenge-as-governance behavior when state authority is unable to bind family factions.",
  },
];

const overreachSimilarity: SimilarityNeighbor[] = [
  {
    workspace_id: "corpus-imperial-athens-sicily",
    conflict_name: "Athens-Sicily 415 BCE",
    semantic_dist: 0.13,
    topological_dist: 0.19,
    combined_dist: 0.16,
    explanation:
      "A distant campaign consumes force projection capacity and turns tactical initiative into strategic vulnerability.",
  },
  {
    workspace_id: "corpus-imperial-hitler-russia",
    conflict_name: "Germany-Russia 1941",
    semantic_dist: 0.16,
    topological_dist: 0.22,
    combined_dist: 0.19,
    explanation:
      "The closest modern neighbour repeats the same logistics-weather-attrition feedback loop and capital-target fixation.",
  },
  {
    workspace_id: "corpus-imperial-vietnam",
    conflict_name: "US-Vietnam 1965-73",
    semantic_dist: 0.31,
    topological_dist: 0.37,
    combined_dist: 0.34,
    explanation:
      "The topology diverges through insurgency, but the overreach signature remains visible in domestic constraint accumulation.",
  },
];

const successorSimilarity: SimilarityNeighbor[] = [
  {
    workspace_id: "corpus-successor-taliban-2021",
    conflict_name: "Taliban 2021",
    semantic_dist: 0.2,
    topological_dist: 0.28,
    combined_dist: 0.24,
    explanation:
      "A spoiler actor becomes a successor authority after external scaffolding around the incumbent collapses.",
  },
  {
    workspace_id: "corpus-successor-rpf-1994",
    conflict_name: "RPF Rwanda 1994",
    semantic_dist: 0.29,
    topological_dist: 0.32,
    combined_dist: 0.31,
    explanation:
      "The successor move is rapid and military, but post-conflict legitimacy mechanisms differ from the Syria case.",
  },
  {
    workspace_id: "corpus-successor-eritrea-1991",
    conflict_name: "Eritrea 1991",
    semantic_dist: 0.34,
    topological_dist: 0.35,
    combined_dist: 0.35,
    explanation:
      "A long-running rebel structure converts battlefield legitimacy into governance, with lower sectarian fragmentation.",
  },
];

const QUESTIONS: CuratedReasoningQuestion[] = [
  {
    id: "R-1",
    scenario_id: "romeo",
    text: "At what Glasl stage does this conflict pivot from objectifiable to intractable, and on which event?",
    stake: "Mediators need to know whether they are still facing loss-of-face dynamics or public threat dynamics.",
    academic_anchor: "Glasl, F. (1999). Confronting Conflict.",
    primary_framework: "glasl",
    symbolic_rules: ["escalation.compute_glasl_stage", "causal_analysis.find_pivot_event"],
    counterfactual_supported: true,
    similarity_supported: false,
    dialectica: result(
      "R-1",
      "glasl",
      "The pivot is Mercutio's death: the graph moves from stage 4-5 into stage 6 and sets up stage 7.",
      "Before Mercutio's death the feud is coalition and face-loss behaviour. The Mercutio_death -> Tybalt_death -> Banishment CAUSED chain introduces retaliatory threat with strategic consequences. That is the deterministic boundary between objectifiable conflict and intractable escalation.",
      ["evt_mercutio_death", "evt_tybalt_death", "evt_banishment"],
      ["ed_mercutio_causes_tybalt", "ed_tybalt_causes_banish"],
      ["escalation.compute_glasl_stage", "causal_analysis.find_pivot_event"],
      0.92,
      0.95,
      0.04
    ),
    llm: llm("The conflict likely escalates after Mercutio is killed, because Romeo retaliates and kills Tybalt. This makes reconciliation much harder, although exact Glasl staging is interpretive."),
    counterfactual: {
      remove_label: "Remove Mercutio death",
      removed_node_ids: ["evt_mercutio_death"],
      removed_edge_ids: ["ed_mercutio_causes_tybalt"],
      result_summary: "Stage remains at 5; Romeo's revenge edge and banishment cascade disappear.",
      diff: "Glasl stage 6 -> 5; double-suicide precondition chain no longer resolves.",
    },
  },
  {
    id: "R-2",
    scenario_id: "romeo",
    text: "Who is the structural spoiler? Quantify by betweenness centrality on de-escalation paths.",
    stake: "Spoilers are the first actor class a peace process has to identify.",
    academic_anchor: "Stedman (1997), Spoiler Problems in Peace Processes.",
    primary_framework: "network_metrics",
    symbolic_rules: ["network_metrics.compute_betweenness", "pattern_matching.identify_spoilers"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("R-2", "network_metrics", "Tybalt is the structural spoiler, with high betweenness on paths that could have de-escalated the feud.", "Tybalt cuts the Romeo-Mercutio-Prince bridge and forces the conflict back into the bilateral family channel. The computed spoiler profile fits Stedman's hard-spoiler template: low settlement compatibility and high path disruption.", ["act_tybalt", "act_romeo", "evt_mercutio_death"], ["ed_tybalt_opposes_romeo"], ["network_metrics.compute_betweenness", "pattern_matching.identify_spoilers"], 0.88, 0.91),
    llm: llm("Tybalt is the obvious spoiler because he is aggressive and refuses peace with Romeo. His killing of Mercutio accelerates the tragedy."),
  },
  {
    id: "R-3",
    scenario_id: "romeo",
    text: "Why does Friar Lawrence's Track-II mediation fail? Diagnose with French/Raven.",
    stake: "Track-II mediators often have expertise and trust but no enforceable authority.",
    academic_anchor: "French & Raven (1959), The Bases of Social Power.",
    primary_framework: "french_raven",
    symbolic_rules: ["power_analysis.compute_power_distribution", "pattern_matching.match_mediator_template"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("R-3", "french_raven", "Friar Lawrence has expert and referent power, but not enough legitimate or coercive power to bind the houses.", "The graph marks him as trusted by Romeo and Juliet and linked to mediation, but not connected to Prince Escalus's enforcement norm. The Paris marriage arrangement requires authority he does not possess, so his Track-II intervention collapses when public obligations return.", ["act_friar", "act_romeo", "act_juliet", "norm_prince_order"], ["ed_friar_mediates"], ["power_analysis.compute_power_distribution", "pattern_matching.match_mediator_template"], 0.84, 0.86),
    llm: llm("Friar Lawrence fails because his secret plan is risky and he lacks authority over the families. He means well, but events outrun him."),
  },
  {
    id: "R-4",
    scenario_id: "romeo",
    text: "If Mercutio survives Act III Scene 1, project the conflict trajectory.",
    stake: "Counterfactual discipline is the daily work of intelligence and mediation analysis.",
    academic_anchor: "Pearl (2009), Causality.",
    primary_framework: "pearl_causal",
    symbolic_rules: ["causal_analysis.do_intervention", "escalation.project_trajectory"],
    counterfactual_supported: true,
    similarity_supported: false,
    dialectica: result("R-4", "pearl_causal", "Without Mercutio_death, the revenge and banishment chain breaks; the projected outcome is stage 4-5 rivalry, not double suicide.", "The intervention deletes the Mercutio_death node and its outgoing CAUSED edge. Romeo no longer has a direct revenge trigger against Tybalt, and the Prince does not banish Romeo for Tybalt's death. Friar Lawrence's mediation remains weak but still available.", ["evt_mercutio_death", "evt_tybalt_death", "evt_banishment"], ["ed_mercutio_causes_tybalt", "ed_tybalt_causes_banish"], ["causal_analysis.do_intervention", "escalation.project_trajectory"], 0.71, 0.82, 0.11),
    llm: llm("If Mercutio survives, Romeo may not kill Tybalt, so the tragedy might be avoided. However Shakespeare could still find another path to conflict."),
    counterfactual: {
      remove_label: "Run do(Mercutio_death = false)",
      removed_node_ids: ["evt_mercutio_death"],
      removed_edge_ids: ["ed_mercutio_causes_tybalt", "ed_tybalt_causes_banish"],
      result_summary: "The conflict remains a stage 5 rivalry with intermittent skirmishes.",
      diff: "Banishment dependency removed; confidence capped at 0.71 for L2 counterfactual uncertainty.",
    },
  },
  {
    id: "R-5",
    scenario_id: "romeo",
    text: "Is the conflict ripe for resolution at the moment of the secret marriage? Compute MHS and MEO.",
    stake: "Mistimed mediation burns credibility before the conflict reaches a hurting stalemate.",
    academic_anchor: "Zartman (1989), Ripe for Resolution.",
    primary_framework: "zartman",
    symbolic_rules: ["ripeness.compute_mhs_meo"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("R-5", "zartman", "Not ripe: pain is low and the opportunity is hidden rather than mutually enticing.", "The graph has no major casualty node before the secret marriage. MHS is therefore low. The marriage is not a public bargain and cannot bind Capulet or Montague, so MEO is also weak. The diagnosis is pre-ripe intervention.", ["act_romeo", "act_juliet", "act_friar", "conf_verona"], ["ed_friar_mediates"], ["ripeness.compute_mhs_meo"], 0.83, 0.9),
    llm: llm("The secret marriage is not enough to resolve the feud because the families do not know about it and are not ready to reconcile."),
  },
  {
    id: "R-6",
    scenario_id: "romeo",
    text: "Which real-world conflicts share this actor-event-norm topology?",
    stake: "Structured comparison turns analyst memory into computable pattern recognition.",
    academic_anchor: "George & Bennett (2005), Case Studies and Theory Development.",
    primary_framework: "pattern_matching",
    symbolic_rules: ["pattern_matching.compute_topology_signature", "community.find_similar_workspaces"],
    counterfactual_supported: false,
    similarity_supported: true,
    dialectica: result("R-6", "pattern_matching", "The closest class is identity-coded vendettas in weak-state contexts, not romantic tragedy.", "The topology is bilateral kin opposition, weak civic enforcement, revenge trigger, and failed mediation. The nearest workspaces are Hatfield-McCoy, Albanian gjakmarrja, and Pashtun badal cases by combined embedding and graph-kernel distance.", ["conf_verona", "evt_mercutio_death", "norm_prince_order"], ["ed_brawl_causes_mercutio", "ed_tybalt_opposes_romeo"], ["pattern_matching.compute_topology_signature", "community.find_similar_workspaces"], 0.87, 0.84),
    llm: llm("Romeo and Juliet resembles other forbidden-love stories such as West Side Story, as well as family feuds like the Hatfields and McCoys."),
    similarity: vendettaSimilarity,
  },
  {
    id: "R-7",
    scenario_id: "romeo",
    text: "What unstated interest does Lord Capulet hold that the play never makes explicit?",
    stake: "Fisher/Ury negotiation depends on detecting interests behind stated positions.",
    academic_anchor: "Fisher & Ury (1981), Getting to Yes.",
    primary_framework: "fisher_ury",
    symbolic_rules: ["pattern_matching.infer_unstated_interests"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("R-7", "fisher_ury", "Capulet's unstated interest is dynastic continuity through a legitimacy-producing marriage alliance.", "The Paris arrangement points toward alliance with the Prince's kin. In graph terms, Juliet becomes a bridge from family honour to civic legitimacy. Romeo cannot offer that hedge because he is structurally inside the opposing faction.", ["act_juliet", "int_dynastic", "norm_prince_order"], ["ed_capulet_interest"], ["pattern_matching.infer_unstated_interests"], 0.82, 0.78),
    llm: llm("Lord Capulet wants social status and a good marriage for Juliet. He likely also wants family honour and obedience."),
  },
  {
    id: "R-8",
    scenario_id: "romeo",
    text: "What intervention would Lederach's conflict transformation framework recommend, and at what timing?",
    stake: "Transformation requires sequencing personal, relational, structural, and cultural work.",
    academic_anchor: "Lederach (2003), The Little Book of Conflict Transformation.",
    primary_framework: "lederach",
    symbolic_rules: ["pattern_matching.match_lederach_levels"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("R-8", "lederach", "The highest priority is structural reform after the double-suicide shock creates a simultaneous pain threshold.", "The Prince's decree has not constrained the noble houses, so another decree is insufficient. A binding reconciliation court plus relational work between houses is the model's recommended sequence; narrative repair follows after structural credibility exists.", ["conf_verona", "norm_prince_order", "act_friar"], ["ed_friar_mediates"], ["pattern_matching.match_lederach_levels"], 0.79, 0.81),
    llm: llm("Lederach would recommend reconciliation, dialogue, and healing between the families after the deaths reveal the cost of hatred."),
  },
  {
    id: "W-1",
    scenario_id: "war_peace",
    text: "How much variance in the 1812 outcome is explained by individual agency vs structural forces?",
    stake: "This operationalizes Tolstoy's great-man critique as a testable causal decomposition.",
    academic_anchor: "Tolstoy, Epilogue II; Carr (1961); Pearl (2009).",
    primary_framework: "pearl_causal",
    symbolic_rules: ["causal_analysis.decompose_variance", "pattern_matching.classify_decision_constraint_density"],
    counterfactual_supported: true,
    similarity_supported: false,
    dialectica: result("W-1", "pearl_causal", "Structural constraints explain roughly two-thirds of the extracted outcome variance; agency remains non-trivial.", "The high-constraint events are logistics, attrition, and winter exposure; the high-discretion events are Smolensk advance, Moscow abandonment, and refusal of negotiation. The model supports Tolstoy's claim but preserves a 0.34 agency component.", ["act_napoleon", "evt_smolensk", "evt_moscow", "pow_attrition"], ["ed_napoleon_advances", "ed_moscow_berezina"], ["causal_analysis.decompose_variance", "pattern_matching.classify_decision_constraint_density"], 0.81, 0.82),
    llm: llm("Tolstoy argues structural forces matter more than individual agency, though leaders like Napoleon and Kutuzov still make important decisions."),
    counterfactual: {
      remove_label: "Remove Smolensk advance",
      removed_node_ids: ["evt_smolensk"],
      removed_edge_ids: ["ed_smolensk_borodino", "ed_napoleon_advances"],
      result_summary: "Agency contribution drops; the Moscow campaign path no longer dominates the outcome.",
      diff: "Agency variance 0.34 -> 0.18; structural constraints remain the majority explanation.",
    },
  },
  {
    id: "W-2",
    scenario_id: "war_peace",
    text: "Was Kutuzov's decision to abandon Moscow rational? Compute his BATNA.",
    stake: "Military withdrawal can be a dominant strategy when attrition curves matter more than territory.",
    academic_anchor: "Fisher & Ury (1981); Brodie (1973), War and Politics.",
    primary_framework: "fisher_ury",
    symbolic_rules: ["power_analysis.compute_batna", "causal_analysis.simulate_attrition_curve"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("W-2", "fisher_ury", "Yes. Kutuzov's BATNA dominates because withdrawal increases French attrition faster than Russian reinforcement loss.", "The Moscow event is connected to attrition advantage rather than defeat alone. Defensive battle would spend Russian force faster; withdrawal externalizes costs onto French logistics. The answer is strategic, not mystical.", ["act_kutuzov", "evt_moscow", "pow_attrition"], ["ed_kutuzov_batna", "ed_moscow_berezina"], ["power_analysis.compute_batna", "causal_analysis.simulate_attrition_curve"], 0.86, 0.87),
    llm: llm("Kutuzov's decision was rational because preserving the army mattered more than defending Moscow."),
  },
  {
    id: "W-3",
    scenario_id: "war_peace",
    text: "Glasl trajectory of the Napoleon-Russia conflict: when does it cross stage 7 -> 8 -> 9?",
    stake: "A literary arc becomes dated stage boundaries in an escalation model.",
    academic_anchor: "Glasl (1999), stages 7-9.",
    primary_framework: "glasl",
    symbolic_rules: ["escalation.compute_glasl_stage", "escalation.compute_trajectory"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("W-3", "glasl", "Niemen marks stage 7, Moscow burning marks stage 8, and Berezina marks stage 9.", "The chain Niemen -> Smolensk -> Borodino -> Moscow -> Berezina turns limited destructive blows into fragmentation and then army destruction as outcome. Each boundary is anchored to an event node.", ["evt_niemen", "evt_moscow", "evt_berezina"], ["ed_niemen_smolensk", "ed_moscow_berezina"], ["escalation.compute_glasl_stage", "escalation.compute_trajectory"], 0.94, 0.95, 0.03),
    llm: llm("The conflict intensifies through invasion, Borodino, Moscow, and the retreat. These episodes fit late Glasl stages."),
  },
  {
    id: "W-4",
    scenario_id: "war_peace",
    text: "Does the partisan irregular fighter materially shift the outcome, or is Tolstoy's portrayal decorative?",
    stake: "Irregular warfare can be a causal layer, not just a colourful narrative detail.",
    academic_anchor: "Beckett (2001); Mao (1937).",
    primary_framework: "network_metrics",
    symbolic_rules: ["network_metrics.compute_edge_contribution", "causal_analysis.decompose_attrition_sources"],
    counterfactual_supported: true,
    similarity_supported: false,
    dialectica: result("W-4", "network_metrics", "Material. The irregular layer increases retreat attrition and materially lowers survival at Berezina.", "The graph attributes a meaningful share of retreat degradation to irregular attacks, though with wider error bars because weather, logistics, and partisan effects overlap in the source text.", ["evt_berezina", "pow_attrition"], ["ed_moscow_berezina"], ["network_metrics.compute_edge_contribution", "causal_analysis.decompose_attrition_sources"], 0.78, 0.76, 0.14),
    llm: llm("Partisan fighters matter because they harass the French retreat, though Tolstoy also uses them to make philosophical points."),
    counterfactual: {
      remove_label: "Remove partisan attrition edges",
      removed_node_ids: [],
      removed_edge_ids: ["ed_moscow_berezina"],
      result_summary: "Projected French survival improves, but logistics and weather still drive collapse.",
      diff: "Berezina survival estimate increases; causal attribution confidence widens.",
    },
  },
  {
    id: "W-5",
    scenario_id: "war_peace",
    text: "Counterfactual: if Napoleon retreats from Smolensk in August 1812, does France retain Continental hegemony through 1815?",
    stake: "Long horizon counterfactuals must show uncertainty rather than a confident alternate history.",
    academic_anchor: "Pearl (2009); Schroeder (1994), The Transformation of European Politics.",
    primary_framework: "pearl_causal",
    symbolic_rules: ["causal_analysis.do_intervention", "pattern_matching.compare_hegemony_trajectory"],
    counterfactual_supported: true,
    similarity_supported: false,
    dialectica: result("W-5", "pearl_causal", "Probable retention through 1813, indeterminate by 1815.", "Deleting the Moscow campaign preserves veterans and changes the 1813 balance, but British naval pressure and Spain remain. The model refuses a confident 1815 answer because uncertainty compounds over multiple years.", ["act_napoleon", "evt_smolensk", "evt_moscow"], ["ed_smolensk_borodino", "ed_borodino_moscow"], ["causal_analysis.do_intervention", "pattern_matching.compare_hegemony_trajectory"], 0.55, 0.68, 0.18),
    llm: llm("If Napoleon had retreated from Smolensk, France might have remained stronger and perhaps preserved dominance longer, but other coalitions would still challenge him."),
    counterfactual: {
      remove_label: "Run do(Moscow campaign = false)",
      removed_node_ids: ["evt_moscow"],
      removed_edge_ids: ["ed_borodino_moscow", "ed_moscow_berezina"],
      result_summary: "French 1813 position improves; 1815 remains unresolved.",
      diff: "Confidence intentionally falls to 0.55 due to horizon length.",
    },
  },
  {
    id: "W-6",
    scenario_id: "war_peace",
    text: "Map structural similarity to other imperial overreach cases.",
    stake: "Buyers need cross-case retrieval by operational class, not keyword resemblance.",
    academic_anchor: "Kennedy (1987), The Rise and Fall of the Great Powers.",
    primary_framework: "pattern_matching",
    symbolic_rules: ["community.find_similar_workspaces"],
    counterfactual_supported: false,
    similarity_supported: true,
    dialectica: result("W-6", "pattern_matching", "The nearest cases are Athens-Sicily, Germany-Russia 1941, and US-Vietnam.", "The embedding-plus-topology signature is imperial overreach: force projection, logistics strain, political objective drift, and terminating attrition. Romeo separates cleanly from this class.", ["conf_1812", "evt_smolensk", "evt_berezina"], ["ed_smolensk_borodino", "ed_moscow_berezina"], ["community.find_similar_workspaces"], 0.84, 0.8),
    llm: llm("Napoleon's invasion is often compared to Hitler's invasion of the Soviet Union, Athens in Sicily, and the United States in Vietnam."),
    similarity: overreachSimilarity,
  },
  {
    id: "W-7",
    scenario_id: "war_peace",
    text: "What does Mayer trust analysis say about the Napoleon-Alexander I dyad before, during, and after?",
    stake: "Trust collapse can be decomposed into ability, benevolence, and integrity signals.",
    academic_anchor: "Mayer, Davis & Schoorman (1995).",
    primary_framework: "mayer_trust",
    symbolic_rules: ["trust_analysis.compute_dyad_trust", "trust_analysis.detect_breach_events"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("W-7", "mayer_trust", "The dyad collapses primarily on integrity, not ability or benevolence.", "Tilsit and Erfurt are fragile trust states; Continental System non-compliance is the integrity breach; 1812 is full trust failure. The model says reconciliation has to restore integrity first.", ["act_napoleon", "act_alexander", "conf_1812"], ["ed_niemen_smolensk"], ["trust_analysis.compute_dyad_trust", "trust_analysis.detect_breach_events"], 0.8, 0.83),
    llm: llm("Napoleon and Alexander's relationship deteriorates after Tilsit as each doubts the other's reliability, culminating in the 1812 invasion."),
  },
  {
    id: "S-1",
    scenario_id: "syria",
    text: "Did Russia's September 2015 intervention cause regime survival? Quantify the counterfactual.",
    stake: "This is a live policy debate about intervention efficacy and regime survival.",
    academic_anchor: "Charap & Geist (2018), Russia's Use of Military Power; Pearl (2009).",
    primary_framework: "pearl_causal",
    symbolic_rules: ["causal_analysis.do_intervention", "causal_analysis.compute_territorial_trajectory"],
    counterfactual_supported: true,
    similarity_supported: false,
    dialectica: result("S-1", "pearl_causal", "Yes. The Russian intervention bought regime survival through the 2016 Aleppo chain and likely extended Assad's rule by years.", "Removing the Russian intervention edge sharply lowers the projected Aleppo recapture probability and regime survival past 2018. The mechanism is air support -> ground tempo -> Aleppo siege -> rebel territorial incoherence. The 2024 collapse is separated as a later structural-scaffolding failure.", ["act_russia", "act_assad", "evt_russia_2015", "evt_aleppo"], ["ed_russia_assad", "ed_russia_aleppo"], ["causal_analysis.do_intervention", "causal_analysis.compute_territorial_trajectory"], 0.89, 0.86, 0.07),
    llm: llm("Russia's intervention was very important to Assad's survival because it added airpower and diplomatic support, though Iran and regime forces also mattered."),
    counterfactual: {
      remove_label: "Remove Russian intervention edge",
      removed_node_ids: ["evt_russia_2015"],
      removed_edge_ids: ["ed_russia_aleppo", "ed_russia_assad"],
      result_summary: "Aleppo recapture probability falls and survival past 2018 becomes unlikely.",
      diff: "Regime survival confidence changes from high to minority-probability counterfactual.",
    },
  },
  {
    id: "S-2",
    scenario_id: "syria",
    text: "When did the conflict cross from Glasl 7 to Glasl 8? Anchor the date on a norm-violation event.",
    stake: "Escalation-stage labels should be tied to events, not adjectives.",
    academic_anchor: "Glasl (1999), stage 8 fragmentation.",
    primary_framework: "glasl",
    symbolic_rules: ["escalation.compute_glasl_stage", "causal_analysis.identify_stage_pivot"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("S-2", "glasl", "The pivot is August-September 2013 around the Ghouta chemical attack and failed enforcement of the red-line norm.", "Ghouta violates the CWC norm node and is followed by accelerated fragmentation: opposition faction multiplication, ISIS expansion, and repeat chemical attacks. The model marks stage 8 by mid-2014.", ["evt_ghouta", "norm_cwc", "conf_syria"], ["ed_ghouta_norm"], ["escalation.compute_glasl_stage", "causal_analysis.identify_stage_pivot"], 0.91, 0.9, 0.05),
    llm: llm("The conflict likely crossed into severe fragmentation after the 2013 Ghouta chemical attack and the growth of ISIS."),
  },
  {
    id: "S-3",
    scenario_id: "syria",
    text: "Why did Russia, Iran, and Turkey bypass Geneva and create the Astana process in 2017? Diagnose the BATNA shift.",
    stake: "Forum choice is often BATNA arithmetic disguised as diplomatic creativity.",
    academic_anchor: "Hill (2018) on Astana; Fisher & Ury BATNA framework.",
    primary_framework: "fisher_ury",
    symbolic_rules: ["power_analysis.compute_batna_shift", "pattern_matching.identify_forum_shift"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("S-3", "fisher_ury", "Astana codified battlefield BATNAs that Geneva could not represent.", "Post-Aleppo Russia has an enforceable survival settlement; Turkey has a YPG-containment objective; Iran has corridor interests. Geneva's transition frame cannot price those BATNAs, so the forum shifts to the actors who can enforce zones on the ground.", ["act_russia", "act_iran", "act_turkey", "evt_astana", "evt_aleppo"], ["ed_aleppo_astana", "ed_iran_corridor"], ["power_analysis.compute_batna_shift", "pattern_matching.identify_forum_shift"], 0.85, 0.83),
    llm: llm("Astana emerged because Russia, Iran, and Turkey had more influence on the ground and wanted a process less dominated by Western demands."),
  },
  {
    id: "S-4",
    scenario_id: "syria",
    text: "Spoiler typology: which armed groups acted as systematic de-escalation spoilers from 2012-2024?",
    stake: "Different spoiler classes require coercion, isolation, or incentives.",
    academic_anchor: "Stedman (1997); Putzel (2010); Cunningham (2006).",
    primary_framework: "pattern_matching",
    symbolic_rules: ["pattern_matching.identify_spoilers", "network_metrics.compute_ceasefire_violation_attribution"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("S-4", "pattern_matching", "ISIS and early HTS fit total-spoiler behaviour; Hezbollah and PYD/SDF are better classified as conditional spoilers.", "The classification changes over time. HTS moves from total spoiler to conditional governance challenger and then successor candidate in 2024. That temporal reclassification is the important signal.", ["act_hts", "act_sdf", "evt_hts_2024"], ["ed_hts_offensive"], ["pattern_matching.identify_spoilers", "network_metrics.compute_ceasefire_violation_attribution"], 0.8, 0.79),
    llm: llm("ISIS, al-Nusra/HTS, and some militia factions often spoiled ceasefires, while other groups were conditional participants."),
  },
  {
    id: "S-5",
    scenario_id: "syria",
    text: "Galtung structural-violence index: change from pre-2011 to 2024. Decompose by direct, structural, cultural.",
    stake: "Negative peace is not positive peace; reconstruction planning depends on the difference.",
    academic_anchor: "Galtung (1969), Violence, Peace, and Peace Research.",
    primary_framework: "galtung",
    symbolic_rules: ["pattern_matching.compute_galtung_indices"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("S-5", "galtung", "Direct, structural, and cultural violence are all higher in 2024 than pre-2011, even after regime collapse.", "The graph separates casualty/displacement violence from institutional collapse and sectarian narrative hardening. A ceasefire could reduce direct violence while structural and cultural violence remain high for a 15-25 year horizon.", ["conf_syria", "evt_daraa", "evt_hts_2024"], ["ed_daraa_conflict", "ed_hts_collapse"], ["pattern_matching.compute_galtung_indices"], 0.83, 0.82),
    llm: llm("Syria's violence worsened dramatically after 2011, with deaths, displacement, institutional collapse, and sectarian narratives."),
  },
  {
    id: "S-6",
    scenario_id: "syria",
    text: "Power asymmetries between Iran-Russia-Turkey-US-Israel as of 2024: French/Raven decomposition.",
    stake: "Leverage is multidimensional; coercive power and legitimacy can diverge sharply.",
    academic_anchor: "French & Raven (1959); Nye (1990).",
    primary_framework: "french_raven",
    symbolic_rules: ["power_analysis.compute_power_distribution", "power_analysis.compute_dyadic_leverage"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("S-6", "french_raven", "Russia holds broad leverage over the regime; Israel's leverage is narrower but highly coercive against Iranian assets.", "The decomposition keeps coercive, reward, legitimate, expert, and referent dimensions separate. It avoids the common mistake of treating legitimacy as the same thing as operational leverage.", ["act_russia", "act_iran", "act_turkey", "act_assad"], ["ed_russia_assad", "ed_iran_corridor", "ed_turkey_hts"], ["power_analysis.compute_power_distribution", "power_analysis.compute_dyadic_leverage"], 0.82, 0.8),
    llm: llm("Russia, Iran, Turkey, the US, and Israel each have different leverage in Syria, with Russia and Iran closest to the regime and Israel focused on Iranian assets."),
  },
  {
    id: "S-7",
    scenario_id: "syria",
    text: "The November-December 2024 HTS offensive: classify the regime collapse as Glasl 9 or Kriesberg settlement.",
    stake: "Collapse, settlement, and mutual destruction lead to very different policy postures.",
    academic_anchor: "Glasl (1999); Kriesberg (1991).",
    primary_framework: "glasl_kriesberg",
    symbolic_rules: ["escalation.compute_glasl_stage", "pattern_matching.match_kriesberg_phase"],
    counterfactual_supported: false,
    similarity_supported: true,
    dialectica: result("S-7", "glasl_kriesberg", "Neither cleanly: it is regime structural collapse through withdrawal of external scaffolding.", "The HTS offensive is necessary but not sufficient. Russia and Iran are stretched by other theatres; regime defensive coherence fails; HTS shifts from spoiler to successor. That raises recurrence risk because successor transitions from armed groups are unstable.", ["act_hts", "evt_hts_2024", "act_russia", "act_iran", "act_assad"], ["ed_hts_offensive", "ed_hts_collapse", "ed_russia_assad"], ["escalation.compute_glasl_stage", "pattern_matching.match_kriesberg_phase"], 0.78, 0.76, 0.13),
    llm: llm("The 2024 offensive would be a regime collapse rather than a negotiated settlement. It could indicate a new phase rather than a final resolution."),
    similarity: successorSimilarity,
  },
  {
    id: "S-8",
    scenario_id: "syria",
    text: "Recurrence probability within 5 years: compute Walter base rate plus structural similarity adjustment.",
    stake: "A recurrence estimate changes donor posture from rebuilding to prevention.",
    academic_anchor: "Walter (2004), Does Conflict Beget Conflict?",
    primary_framework: "pattern_matching",
    symbolic_rules: ["pattern_matching.compute_recurrence_risk"],
    counterfactual_supported: false,
    similarity_supported: false,
    dialectica: result("S-8", "pattern_matching", "The five-year recurrence estimate is about 0.51 with wide but policy-relevant uncertainty.", "Walter's base rate is adjusted upward by high structural violence, spoiler-to-successor transition, and unresolved Kurdish-Arab, Alawite, Druze, Iranian, Turkish, and Israeli security interests. The mechanism is grievance remobilisation plus proxy reactivation.", ["conf_syria", "act_hts", "act_sdf", "int_corridor"], ["ed_iran_corridor", "ed_turkey_hts"], ["pattern_matching.compute_recurrence_risk"], 0.77, 0.74, 0.16),
    llm: llm("The risk of renewed conflict in Syria is high because institutions are weak, armed groups remain, and external actors still have interests."),
  },
];

export function getReasoningScenario(scenarioId: string): ReasoningScenario | undefined {
  const typed = scenarioId as DemoScenarioId;
  const questions = QUESTIONS.filter((question) => question.scenario_id === typed);
  if (!questions.length || !GRAPHS[typed]) return undefined;
  const title =
    typed === "romeo" ? "Romeo and Juliet" : typed === "war_peace" ? "War and Peace" : "Syria 2011-2024";
  const subtitle =
    typed === "romeo"
      ? "Vendetta, failed mediation, and escalation theory"
      : typed === "war_peace"
        ? "Agency, structure, logistics, and imperial overreach"
        : "Intervention, fragmentation, spoilers, and recurrence risk";
  return {
    id: typed,
    title,
    subtitle,
    workspace_id: `demo-${typed.replace("_", "-")}`,
    graph: GRAPHS[typed],
    questions,
  };
}

export function cloneGraph(graph: GraphData): GraphData {
  return {
    nodes: graph.nodes.map((n) => ({ ...n, properties: { ...n.properties } })),
    links: graph.links.map((l) => ({ ...l })),
  };
}
